### ISSUE TITLE
Adds python versions to ci.yml

### ISSUE THREAD

**Issue by mxochicale** [SciKit-Surgery/PythonTemplate#61]
Adds python version and updates `actions/checkout@v3`, `actions/setup-python@v4` in ci.yml

```
        experimental: [false]
        include:
          - python-ver: 3.9
            os: ubuntu-latest
            experimental: true
          - python-ver: 3.9
            os: macos-latest
            experimental: true
          - python-ver: 3.9
            os: windows-latest
            experimental: true
          - python-ver: '3.10'
            os: ubuntu-latest
            experimental: true
          - python-ver: '3.10'
            os: macos-latest
            experimental: true
          - python-ver: '3.10'
            os: windows-latest
            experimental: true
          - python-ver: 3.11
            os: ubuntu-latest
            experimental: true
          - python-ver: 3.11
            os: macos-latest
            experimental: true
          - python-ver: 3.11
            os: windows-latest
            experimental: true
          - python-ver: 3.12-dev
            os: ubuntu-latest
            experimental: true
          - python-ver: 3.12-dev
            os: macos-latest
            experimental: true
          - python-ver: 3.12-dev
            os: windows-latest
            experimental: true
```
